### ISSUE TITLE
Kotlin: Crash on resume / orientation change

### ISSUE THREAD

**Issue by sebastianmarschall** [patloew/countries#2]
Device: Nexus 6P
Android 7.1.1

`02-14 15:38:55.521 20057-20057/com.patloew.countries.dev E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: com.patloew.countries.dev, PID: 20057
                                                                           java.lang.RuntimeException: Unable to start activity ComponentInfo{com.patloew.countries.dev/com.patloew.countries.ui.main.MainActivity}: kotlin.UninitializedPropertyAccessException: lateinit property activityComponent has not been initialized
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                               at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4519)
                                                                               at android.app.ActivityThread.-wrap19(ActivityThread.java)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1483)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:154)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                            Caused by: kotlin.UninitializedPropertyAccessException: lateinit property activityComponent has not been initialized
                                                                               at com.patloew.countries.ui.base.BaseActivity.getActivityComponent$app_devBackendDebug(BaseActivity.kt:66)
                                                                               at com.patloew.countries.ui.base.BaseFragment.onAttach(BaseFragment.kt:90)
                                                                               at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1231)
                                                                               at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                               at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                               at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:2883)
                                                                               at android.support.v4.app.FragmentController.dispatchCreate(FragmentController.java:190)
                                                                               at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:353)
                                                                               at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:85)
                                                                               at com.patloew.countries.ui.base.BaseActivity.onCreate(BaseActivity.kt:76)
                                                                               at com.patloew.countries.ui.main.MainActivity.onCreate(MainActivity.kt:38)
                                                                               at android.app.Activity.performCreate(Activity.java:6679)
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
                                                                               at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4519) 
                                                                               at android.app.ActivityThread.-wrap19(ActivityThread.java) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1483) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                               at android.os.Looper.loop(Looper.java:154) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) `

**Comment by patloew** [comment]
Thanks for reporting. This is now fixed.
