### ISSUE TITLE
ClassNotFoundException when unmarshalling: io.realm.NeedRealmProxy$$Parcelable #4459

### ISSUE THREAD

**Issue by maelfosso** [patloew/countries#4]
Hi,

Please I follow your tutorial [https://nullpointer.wtf/android/using-retrofit-realm-parceler/](Using Retrofit with Realm and Parceler) but I always have this error

```
android.os.BadParcelableException: ClassNotFoundException when unmarshalling: io.realm.NeedRealmProxy$$Parcelable
at android.os.Parcel.readException(Parcel.java:1427)
at android.os.Parcel.readException(Parcel.java:1379)
at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:1761)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1411)
at android.app.Activity.startActivityForResult(Activity.java:3351)
at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
at android.support.v4.app.ActivityCompatJB.startActivityForResult(ActivityCompatJB.java:30)
 at android.support.v4.app.ActivityCompat.startActivityForResult(ActivityCompat.java:146)
at android.support.v4.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:932)
at android.support.v4.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:1047)
at android.support.v4.app.Fragment.startActivity(Fragment.java:940)
 at com.nkapsi.ui.fragment.HomeFragment.onTaskClick(HomeFragment.java:201)
```

I got that error when running this snippet of code from a fragment ```HomeFragment```
```java
public void onTaskClick(View view, Need need, int position) {
        Log.d(TAG, "onTaskClick() - " + need.toString());

        Intent intent = new Intent(getActivity(), TaskDetailsActivity.class);

        Bundle bundle = new Bundle();
        bundle.putParcelable(TaskDetailsActivity.EXTRA_OBJ_NEED, Parcels.wrap(need));

        startActivity(intent, bundle);
    }
```

Here is ```Need.java```
```java
@Parcel(implementations = {NeedRealmProxy.class}, value = Parcel.Serialization.FIELD, analyze = { Need.class })
public class Need extends RealmObject implements Serializable {

    @PrimaryKey
    @SerializedName("_id")
    private String id;

    @SerializedName("created")
    private Date created;

    @SerializedName("status")
    private String status;

    @SerializedName("fees")
    float fees;

    @SerializedName("user")
    private User user;

    @ParcelPropertyConverter(RealmListParcelConverter.class)
    @SerializedName("places")
    private RealmList<Place> places;

    @SerializedName("user_location")
    private Place userLocation;

    @ParcelPropertyConverter(RealmListParcelConverter.class)
    @SerializedName("items_ordered")
    private RealmList<ItemOrdered> itemsOrdered;

    @ParcelPropertyConverter(RealmListParcelConverter.class)
    @SerializedName("movings")
    private RealmList<Moving> movings;

    @ParcelPropertyConverter(RealmListParcelConverter.class)
    @SerializedName("messages")
    private RealmList<Message> messages;

    @SerializedName("run")
    private Run run;


    public Need() {}

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public List<Place> getPlaces() {
        return places;
    }

    public List<ItemOrdered> getItemsOrdered() {
        return itemsOrdered;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public Double getAmount() {
        double p = 0;
        for (ItemOrdered e: itemsOrdered) {
            if (e.getItem().getPrice() != null) {
                p += e.getItem().getPrice() * e.getQuantity();
            }
        }

        return p;
    }

    public Place getUserLocation() {
        return userLocation;
    }

    public void setUserLocation(Place userLocation) {
        this.userLocation = userLocation;
    }

    public Date getCreated() {
        return created;
    }

    public String getCreatedFormatted() {
        SimpleDateFormat format = new SimpleDateFormat("MMM dd, HH:mm");

        return format.format(created);
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    public String getStatus() {
        return status;
    }

    public List<Message> getMessages() {
        return messages;
    }

    public Run getRun() {
        return this.run;
    }

    public List<Moving> getMovings() {
        return movings;
    }

    public void setMovings(RealmList<Moving> movings) {
        this.movings = movings;
    }

    public float getFees() {
        return fees;
    }

    public void setFees(float fees) {
        this.fees = fees;
    }

    public void setPlaces(RealmList<Place> places) {
        this.places = places;
    }

    public void setItemsOrdered(RealmList<ItemOrdered> itemsOrdered) {
        this.itemsOrdered = itemsOrdered;
    }

    public void setMessages(RealmList<Message> messages) {
        this.messages = messages;
    }

    @Override
    public String toString() {
        return "Need{" +
                "id= '" + id + '\'' +
                ", movings='" + movings.size() + '\'' +
                ", places=" + places.size() +
                ", itemsOrdered=" + itemsOrdered.size() +
                ", userLocation=" + userLocation.getLng() + "," + userLocation.getLat() +
                ", user=" + user +
                '}';
    }
}
```

Here is ```RealmListParcelConverter.java```
```java
public class RealmListParcelConverter implements
        TypeRangeParcelConverter<RealmList<? extends RealmObject>, RealmList<? extends RealmObject>> {
    private static final int NULL = -1;

    @Override
    public void toParcel(RealmList<? extends RealmObject> input, android.os.Parcel parcel) {
        parcel.writeInt(input == null ? NULL : input.size());
        if (input != null) {
            for (RealmObject item : input) {
                parcel.writeParcelable(Parcels.wrap(item), 0);
            }
        }
    }

    @Override
    public RealmList fromParcel(android.os.Parcel parcel) {
        int size = parcel.readInt();
        RealmList list = new RealmList();
        for (int i=0; i<size; i++) {
            Parcelable parcelable = parcel.readParcelable(getClass().getClassLoader());
            list.add((RealmObject) Parcels.unwrap(parcelable));
        }
        return list;
    }
}
```

Please help me to solve this error .

**Comment by patloew** [comment]
Try setting the extra on the intent, and not by using [startActivity(Activity, Bundle)](https://developer.android.com/reference/android/content/Context.html#startActivity(android.content.Intent,%20android.os.Bundle)). Also, please try asking your question on StackOverflow, which is the more appropriate place for questions like these.
